# file for configuring how GitHub publishes the Jekyll site
# themes I like: dinky, minima, minimal, 

theme: minima
title: Jocelyne Shimin Sze
description: A space to think and reflect
header_pages: 
  - about.md
